import Hedetniemi.Round4.WeightRows.Batch00
import Hedetniemi.Round4.WeightRows.Batch01
import Hedetniemi.Round4.WeightRows.Batch02
import Hedetniemi.Round4.WeightRows.Batch03
import Hedetniemi.Round4.WeightRows.Batch04
import Hedetniemi.Round4.WeightRows.Batch05
import Hedetniemi.Round4.WeightRows.Batch06
import Hedetniemi.Round4.WeightRows.Batch07
import Hedetniemi.Round4.WeightRows.Batch08
import Hedetniemi.Round4.WeightRows.Batch09
import Hedetniemi.Round4.WeightRows.Batch10
import Hedetniemi.Round4.WeightRows.Batch11
import Hedetniemi.Round4.WeightRows.Batch12
import Hedetniemi.Round4.WeightRows.Batch13
import Hedetniemi.Round4.WeightRows.Batch14
import Hedetniemi.Round4.WeightRows.Batch15
import Hedetniemi.Round4.WeightRows.Batch16
import Hedetniemi.Round4.WeightRows.Batch17
import Hedetniemi.Round4.WeightRows.Batch18
import Hedetniemi.Round4.WeightRows.Batch19
import Hedetniemi.Round4.WeightRows.Batch20
import Hedetniemi.Round4.WeightRows.Batch21
import Hedetniemi.Round4.WeightRows.Batch22
import Hedetniemi.Round4.WeightRows.Batch23
import Hedetniemi.Round4.WeightRows.Batch24
import Hedetniemi.Round4.WeightRows.Batch25
import Hedetniemi.Round4.WeightRows.Batch26
import Hedetniemi.Round4.WeightRows.Batch27
import Hedetniemi.Round4.WeightRows.Batch28
import Hedetniemi.Round4.WeightRows.Batch29
import Hedetniemi.Round4.WeightRows.Batch30
import Hedetniemi.Round4.WeightRows.Batch31
import Hedetniemi.Round4.WeightRows.Batch32
import Hedetniemi.Round4.WeightRows.Batch33
import Hedetniemi.Round4.WeightRows.Batch34
import Hedetniemi.Round4.WeightRows.Batch35
import Hedetniemi.Round4.WeightRows.Batch36
import Hedetniemi.Round4.WeightRows.Batch37
import Hedetniemi.Round4.WeightRows.Batch38
import Hedetniemi.Round4.WeightRows.Batch39
import Hedetniemi.Round4.WeightRows.Batch40
import Hedetniemi.Round4.WeightRows.Batch41
import Hedetniemi.Round4.WeightRows.Batch42
import Hedetniemi.Round4.WeightRows.Batch43
import Hedetniemi.Round4.WeightRows.Batch44
import Hedetniemi.Round4.WeightRows.Batch45
import Hedetniemi.Round4.WeightRows.Batch46
import Hedetniemi.Round4.WeightRows.Batch47
import Hedetniemi.Round4.WeightRows.Batch48
import Hedetniemi.Round4.WeightRows.Batch49
namespace Hedetniemi.Round4
set_option maxRecDepth 1000000
set_option maxHeartbeats 0
set_option exponentiation.threshold 100000

theorem weightedRow_block (i : Fin 197) (h : Fin 4) :
    weightedSparseRow (blockIndex i h) = weightedRowExpected (blockIndex i h) := by
  fin_cases h
  · fin_cases i
    · exact weighted_row_0
    · exact weighted_row_4
    · exact weighted_row_8
    · exact weighted_row_12
    · exact weighted_row_16
    · exact weighted_row_20
    · exact weighted_row_24
    · exact weighted_row_28
    · exact weighted_row_32
    · exact weighted_row_36
    · exact weighted_row_40
    · exact weighted_row_44
    · exact weighted_row_48
    · exact weighted_row_52
    · exact weighted_row_56
    · exact weighted_row_60
    · exact weighted_row_64
    · exact weighted_row_68
    · exact weighted_row_72
    · exact weighted_row_76
    · exact weighted_row_80
    · exact weighted_row_84
    · exact weighted_row_88
    · exact weighted_row_92
    · exact weighted_row_96
    · exact weighted_row_100
    · exact weighted_row_104
    · exact weighted_row_108
    · exact weighted_row_112
    · exact weighted_row_116
    · exact weighted_row_120
    · exact weighted_row_124
    · exact weighted_row_128
    · exact weighted_row_132
    · exact weighted_row_136
    · exact weighted_row_140
    · exact weighted_row_144
    · exact weighted_row_148
    · exact weighted_row_152
    · exact weighted_row_156
    · exact weighted_row_160
    · exact weighted_row_164
    · exact weighted_row_168
    · exact weighted_row_172
    · exact weighted_row_176
    · exact weighted_row_180
    · exact weighted_row_184
    · exact weighted_row_188
    · exact weighted_row_192
    · exact weighted_row_196
    · exact weighted_row_200
    · exact weighted_row_204
    · exact weighted_row_208
    · exact weighted_row_212
    · exact weighted_row_216
    · exact weighted_row_220
    · exact weighted_row_224
    · exact weighted_row_228
    · exact weighted_row_232
    · exact weighted_row_236
    · exact weighted_row_240
    · exact weighted_row_244
    · exact weighted_row_248
    · exact weighted_row_252
    · exact weighted_row_256
    · exact weighted_row_260
    · exact weighted_row_264
    · exact weighted_row_268
    · exact weighted_row_272
    · exact weighted_row_276
    · exact weighted_row_280
    · exact weighted_row_284
    · exact weighted_row_288
    · exact weighted_row_292
    · exact weighted_row_296
    · exact weighted_row_300
    · exact weighted_row_304
    · exact weighted_row_308
    · exact weighted_row_312
    · exact weighted_row_316
    · exact weighted_row_320
    · exact weighted_row_324
    · exact weighted_row_328
    · exact weighted_row_332
    · exact weighted_row_336
    · exact weighted_row_340
    · exact weighted_row_344
    · exact weighted_row_348
    · exact weighted_row_352
    · exact weighted_row_356
    · exact weighted_row_360
    · exact weighted_row_364
    · exact weighted_row_368
    · exact weighted_row_372
    · exact weighted_row_376
    · exact weighted_row_380
    · exact weighted_row_384
    · exact weighted_row_388
    · exact weighted_row_392
    · exact weighted_row_396
    · exact weighted_row_400
    · exact weighted_row_404
    · exact weighted_row_408
    · exact weighted_row_412
    · exact weighted_row_416
    · exact weighted_row_420
    · exact weighted_row_424
    · exact weighted_row_428
    · exact weighted_row_432
    · exact weighted_row_436
    · exact weighted_row_440
    · exact weighted_row_444
    · exact weighted_row_448
    · exact weighted_row_452
    · exact weighted_row_456
    · exact weighted_row_460
    · exact weighted_row_464
    · exact weighted_row_468
    · exact weighted_row_472
    · exact weighted_row_476
    · exact weighted_row_480
    · exact weighted_row_484
    · exact weighted_row_488
    · exact weighted_row_492
    · exact weighted_row_496
    · exact weighted_row_500
    · exact weighted_row_504
    · exact weighted_row_508
    · exact weighted_row_512
    · exact weighted_row_516
    · exact weighted_row_520
    · exact weighted_row_524
    · exact weighted_row_528
    · exact weighted_row_532
    · exact weighted_row_536
    · exact weighted_row_540
    · exact weighted_row_544
    · exact weighted_row_548
    · exact weighted_row_552
    · exact weighted_row_556
    · exact weighted_row_560
    · exact weighted_row_564
    · exact weighted_row_568
    · exact weighted_row_572
    · exact weighted_row_576
    · exact weighted_row_580
    · exact weighted_row_584
    · exact weighted_row_588
    · exact weighted_row_592
    · exact weighted_row_596
    · exact weighted_row_600
    · exact weighted_row_604
    · exact weighted_row_608
    · exact weighted_row_612
    · exact weighted_row_616
    · exact weighted_row_620
    · exact weighted_row_624
    · exact weighted_row_628
    · exact weighted_row_632
    · exact weighted_row_636
    · exact weighted_row_640
    · exact weighted_row_644
    · exact weighted_row_648
    · exact weighted_row_652
    · exact weighted_row_656
    · exact weighted_row_660
    · exact weighted_row_664
    · exact weighted_row_668
    · exact weighted_row_672
    · exact weighted_row_676
    · exact weighted_row_680
    · exact weighted_row_684
    · exact weighted_row_688
    · exact weighted_row_692
    · exact weighted_row_696
    · exact weighted_row_700
    · exact weighted_row_704
    · exact weighted_row_708
    · exact weighted_row_712
    · exact weighted_row_716
    · exact weighted_row_720
    · exact weighted_row_724
    · exact weighted_row_728
    · exact weighted_row_732
    · exact weighted_row_736
    · exact weighted_row_740
    · exact weighted_row_744
    · exact weighted_row_748
    · exact weighted_row_752
    · exact weighted_row_756
    · exact weighted_row_760
    · exact weighted_row_764
    · exact weighted_row_768
    · exact weighted_row_772
    · exact weighted_row_776
    · exact weighted_row_780
    · exact weighted_row_784
  · fin_cases i
    · exact weighted_row_1
    · exact weighted_row_5
    · exact weighted_row_9
    · exact weighted_row_13
    · exact weighted_row_17
    · exact weighted_row_21
    · exact weighted_row_25
    · exact weighted_row_29
    · exact weighted_row_33
    · exact weighted_row_37
    · exact weighted_row_41
    · exact weighted_row_45
    · exact weighted_row_49
    · exact weighted_row_53
    · exact weighted_row_57
    · exact weighted_row_61
    · exact weighted_row_65
    · exact weighted_row_69
    · exact weighted_row_73
    · exact weighted_row_77
    · exact weighted_row_81
    · exact weighted_row_85
    · exact weighted_row_89
    · exact weighted_row_93
    · exact weighted_row_97
    · exact weighted_row_101
    · exact weighted_row_105
    · exact weighted_row_109
    · exact weighted_row_113
    · exact weighted_row_117
    · exact weighted_row_121
    · exact weighted_row_125
    · exact weighted_row_129
    · exact weighted_row_133
    · exact weighted_row_137
    · exact weighted_row_141
    · exact weighted_row_145
    · exact weighted_row_149
    · exact weighted_row_153
    · exact weighted_row_157
    · exact weighted_row_161
    · exact weighted_row_165
    · exact weighted_row_169
    · exact weighted_row_173
    · exact weighted_row_177
    · exact weighted_row_181
    · exact weighted_row_185
    · exact weighted_row_189
    · exact weighted_row_193
    · exact weighted_row_197
    · exact weighted_row_201
    · exact weighted_row_205
    · exact weighted_row_209
    · exact weighted_row_213
    · exact weighted_row_217
    · exact weighted_row_221
    · exact weighted_row_225
    · exact weighted_row_229
    · exact weighted_row_233
    · exact weighted_row_237
    · exact weighted_row_241
    · exact weighted_row_245
    · exact weighted_row_249
    · exact weighted_row_253
    · exact weighted_row_257
    · exact weighted_row_261
    · exact weighted_row_265
    · exact weighted_row_269
    · exact weighted_row_273
    · exact weighted_row_277
    · exact weighted_row_281
    · exact weighted_row_285
    · exact weighted_row_289
    · exact weighted_row_293
    · exact weighted_row_297
    · exact weighted_row_301
    · exact weighted_row_305
    · exact weighted_row_309
    · exact weighted_row_313
    · exact weighted_row_317
    · exact weighted_row_321
    · exact weighted_row_325
    · exact weighted_row_329
    · exact weighted_row_333
    · exact weighted_row_337
    · exact weighted_row_341
    · exact weighted_row_345
    · exact weighted_row_349
    · exact weighted_row_353
    · exact weighted_row_357
    · exact weighted_row_361
    · exact weighted_row_365
    · exact weighted_row_369
    · exact weighted_row_373
    · exact weighted_row_377
    · exact weighted_row_381
    · exact weighted_row_385
    · exact weighted_row_389
    · exact weighted_row_393
    · exact weighted_row_397
    · exact weighted_row_401
    · exact weighted_row_405
    · exact weighted_row_409
    · exact weighted_row_413
    · exact weighted_row_417
    · exact weighted_row_421
    · exact weighted_row_425
    · exact weighted_row_429
    · exact weighted_row_433
    · exact weighted_row_437
    · exact weighted_row_441
    · exact weighted_row_445
    · exact weighted_row_449
    · exact weighted_row_453
    · exact weighted_row_457
    · exact weighted_row_461
    · exact weighted_row_465
    · exact weighted_row_469
    · exact weighted_row_473
    · exact weighted_row_477
    · exact weighted_row_481
    · exact weighted_row_485
    · exact weighted_row_489
    · exact weighted_row_493
    · exact weighted_row_497
    · exact weighted_row_501
    · exact weighted_row_505
    · exact weighted_row_509
    · exact weighted_row_513
    · exact weighted_row_517
    · exact weighted_row_521
    · exact weighted_row_525
    · exact weighted_row_529
    · exact weighted_row_533
    · exact weighted_row_537
    · exact weighted_row_541
    · exact weighted_row_545
    · exact weighted_row_549
    · exact weighted_row_553
    · exact weighted_row_557
    · exact weighted_row_561
    · exact weighted_row_565
    · exact weighted_row_569
    · exact weighted_row_573
    · exact weighted_row_577
    · exact weighted_row_581
    · exact weighted_row_585
    · exact weighted_row_589
    · exact weighted_row_593
    · exact weighted_row_597
    · exact weighted_row_601
    · exact weighted_row_605
    · exact weighted_row_609
    · exact weighted_row_613
    · exact weighted_row_617
    · exact weighted_row_621
    · exact weighted_row_625
    · exact weighted_row_629
    · exact weighted_row_633
    · exact weighted_row_637
    · exact weighted_row_641
    · exact weighted_row_645
    · exact weighted_row_649
    · exact weighted_row_653
    · exact weighted_row_657
    · exact weighted_row_661
    · exact weighted_row_665
    · exact weighted_row_669
    · exact weighted_row_673
    · exact weighted_row_677
    · exact weighted_row_681
    · exact weighted_row_685
    · exact weighted_row_689
    · exact weighted_row_693
    · exact weighted_row_697
    · exact weighted_row_701
    · exact weighted_row_705
    · exact weighted_row_709
    · exact weighted_row_713
    · exact weighted_row_717
    · exact weighted_row_721
    · exact weighted_row_725
    · exact weighted_row_729
    · exact weighted_row_733
    · exact weighted_row_737
    · exact weighted_row_741
    · exact weighted_row_745
    · exact weighted_row_749
    · exact weighted_row_753
    · exact weighted_row_757
    · exact weighted_row_761
    · exact weighted_row_765
    · exact weighted_row_769
    · exact weighted_row_773
    · exact weighted_row_777
    · exact weighted_row_781
    · exact weighted_row_785
  · fin_cases i
    · exact weighted_row_2
    · exact weighted_row_6
    · exact weighted_row_10
    · exact weighted_row_14
    · exact weighted_row_18
    · exact weighted_row_22
    · exact weighted_row_26
    · exact weighted_row_30
    · exact weighted_row_34
    · exact weighted_row_38
    · exact weighted_row_42
    · exact weighted_row_46
    · exact weighted_row_50
    · exact weighted_row_54
    · exact weighted_row_58
    · exact weighted_row_62
    · exact weighted_row_66
    · exact weighted_row_70
    · exact weighted_row_74
    · exact weighted_row_78
    · exact weighted_row_82
    · exact weighted_row_86
    · exact weighted_row_90
    · exact weighted_row_94
    · exact weighted_row_98
    · exact weighted_row_102
    · exact weighted_row_106
    · exact weighted_row_110
    · exact weighted_row_114
    · exact weighted_row_118
    · exact weighted_row_122
    · exact weighted_row_126
    · exact weighted_row_130
    · exact weighted_row_134
    · exact weighted_row_138
    · exact weighted_row_142
    · exact weighted_row_146
    · exact weighted_row_150
    · exact weighted_row_154
    · exact weighted_row_158
    · exact weighted_row_162
    · exact weighted_row_166
    · exact weighted_row_170
    · exact weighted_row_174
    · exact weighted_row_178
    · exact weighted_row_182
    · exact weighted_row_186
    · exact weighted_row_190
    · exact weighted_row_194
    · exact weighted_row_198
    · exact weighted_row_202
    · exact weighted_row_206
    · exact weighted_row_210
    · exact weighted_row_214
    · exact weighted_row_218
    · exact weighted_row_222
    · exact weighted_row_226
    · exact weighted_row_230
    · exact weighted_row_234
    · exact weighted_row_238
    · exact weighted_row_242
    · exact weighted_row_246
    · exact weighted_row_250
    · exact weighted_row_254
    · exact weighted_row_258
    · exact weighted_row_262
    · exact weighted_row_266
    · exact weighted_row_270
    · exact weighted_row_274
    · exact weighted_row_278
    · exact weighted_row_282
    · exact weighted_row_286
    · exact weighted_row_290
    · exact weighted_row_294
    · exact weighted_row_298
    · exact weighted_row_302
    · exact weighted_row_306
    · exact weighted_row_310
    · exact weighted_row_314
    · exact weighted_row_318
    · exact weighted_row_322
    · exact weighted_row_326
    · exact weighted_row_330
    · exact weighted_row_334
    · exact weighted_row_338
    · exact weighted_row_342
    · exact weighted_row_346
    · exact weighted_row_350
    · exact weighted_row_354
    · exact weighted_row_358
    · exact weighted_row_362
    · exact weighted_row_366
    · exact weighted_row_370
    · exact weighted_row_374
    · exact weighted_row_378
    · exact weighted_row_382
    · exact weighted_row_386
    · exact weighted_row_390
    · exact weighted_row_394
    · exact weighted_row_398
    · exact weighted_row_402
    · exact weighted_row_406
    · exact weighted_row_410
    · exact weighted_row_414
    · exact weighted_row_418
    · exact weighted_row_422
    · exact weighted_row_426
    · exact weighted_row_430
    · exact weighted_row_434
    · exact weighted_row_438
    · exact weighted_row_442
    · exact weighted_row_446
    · exact weighted_row_450
    · exact weighted_row_454
    · exact weighted_row_458
    · exact weighted_row_462
    · exact weighted_row_466
    · exact weighted_row_470
    · exact weighted_row_474
    · exact weighted_row_478
    · exact weighted_row_482
    · exact weighted_row_486
    · exact weighted_row_490
    · exact weighted_row_494
    · exact weighted_row_498
    · exact weighted_row_502
    · exact weighted_row_506
    · exact weighted_row_510
    · exact weighted_row_514
    · exact weighted_row_518
    · exact weighted_row_522
    · exact weighted_row_526
    · exact weighted_row_530
    · exact weighted_row_534
    · exact weighted_row_538
    · exact weighted_row_542
    · exact weighted_row_546
    · exact weighted_row_550
    · exact weighted_row_554
    · exact weighted_row_558
    · exact weighted_row_562
    · exact weighted_row_566
    · exact weighted_row_570
    · exact weighted_row_574
    · exact weighted_row_578
    · exact weighted_row_582
    · exact weighted_row_586
    · exact weighted_row_590
    · exact weighted_row_594
    · exact weighted_row_598
    · exact weighted_row_602
    · exact weighted_row_606
    · exact weighted_row_610
    · exact weighted_row_614
    · exact weighted_row_618
    · exact weighted_row_622
    · exact weighted_row_626
    · exact weighted_row_630
    · exact weighted_row_634
    · exact weighted_row_638
    · exact weighted_row_642
    · exact weighted_row_646
    · exact weighted_row_650
    · exact weighted_row_654
    · exact weighted_row_658
    · exact weighted_row_662
    · exact weighted_row_666
    · exact weighted_row_670
    · exact weighted_row_674
    · exact weighted_row_678
    · exact weighted_row_682
    · exact weighted_row_686
    · exact weighted_row_690
    · exact weighted_row_694
    · exact weighted_row_698
    · exact weighted_row_702
    · exact weighted_row_706
    · exact weighted_row_710
    · exact weighted_row_714
    · exact weighted_row_718
    · exact weighted_row_722
    · exact weighted_row_726
    · exact weighted_row_730
    · exact weighted_row_734
    · exact weighted_row_738
    · exact weighted_row_742
    · exact weighted_row_746
    · exact weighted_row_750
    · exact weighted_row_754
    · exact weighted_row_758
    · exact weighted_row_762
    · exact weighted_row_766
    · exact weighted_row_770
    · exact weighted_row_774
    · exact weighted_row_778
    · exact weighted_row_782
    · exact weighted_row_786
  · fin_cases i
    · exact weighted_row_3
    · exact weighted_row_7
    · exact weighted_row_11
    · exact weighted_row_15
    · exact weighted_row_19
    · exact weighted_row_23
    · exact weighted_row_27
    · exact weighted_row_31
    · exact weighted_row_35
    · exact weighted_row_39
    · exact weighted_row_43
    · exact weighted_row_47
    · exact weighted_row_51
    · exact weighted_row_55
    · exact weighted_row_59
    · exact weighted_row_63
    · exact weighted_row_67
    · exact weighted_row_71
    · exact weighted_row_75
    · exact weighted_row_79
    · exact weighted_row_83
    · exact weighted_row_87
    · exact weighted_row_91
    · exact weighted_row_95
    · exact weighted_row_99
    · exact weighted_row_103
    · exact weighted_row_107
    · exact weighted_row_111
    · exact weighted_row_115
    · exact weighted_row_119
    · exact weighted_row_123
    · exact weighted_row_127
    · exact weighted_row_131
    · exact weighted_row_135
    · exact weighted_row_139
    · exact weighted_row_143
    · exact weighted_row_147
    · exact weighted_row_151
    · exact weighted_row_155
    · exact weighted_row_159
    · exact weighted_row_163
    · exact weighted_row_167
    · exact weighted_row_171
    · exact weighted_row_175
    · exact weighted_row_179
    · exact weighted_row_183
    · exact weighted_row_187
    · exact weighted_row_191
    · exact weighted_row_195
    · exact weighted_row_199
    · exact weighted_row_203
    · exact weighted_row_207
    · exact weighted_row_211
    · exact weighted_row_215
    · exact weighted_row_219
    · exact weighted_row_223
    · exact weighted_row_227
    · exact weighted_row_231
    · exact weighted_row_235
    · exact weighted_row_239
    · exact weighted_row_243
    · exact weighted_row_247
    · exact weighted_row_251
    · exact weighted_row_255
    · exact weighted_row_259
    · exact weighted_row_263
    · exact weighted_row_267
    · exact weighted_row_271
    · exact weighted_row_275
    · exact weighted_row_279
    · exact weighted_row_283
    · exact weighted_row_287
    · exact weighted_row_291
    · exact weighted_row_295
    · exact weighted_row_299
    · exact weighted_row_303
    · exact weighted_row_307
    · exact weighted_row_311
    · exact weighted_row_315
    · exact weighted_row_319
    · exact weighted_row_323
    · exact weighted_row_327
    · exact weighted_row_331
    · exact weighted_row_335
    · exact weighted_row_339
    · exact weighted_row_343
    · exact weighted_row_347
    · exact weighted_row_351
    · exact weighted_row_355
    · exact weighted_row_359
    · exact weighted_row_363
    · exact weighted_row_367
    · exact weighted_row_371
    · exact weighted_row_375
    · exact weighted_row_379
    · exact weighted_row_383
    · exact weighted_row_387
    · exact weighted_row_391
    · exact weighted_row_395
    · exact weighted_row_399
    · exact weighted_row_403
    · exact weighted_row_407
    · exact weighted_row_411
    · exact weighted_row_415
    · exact weighted_row_419
    · exact weighted_row_423
    · exact weighted_row_427
    · exact weighted_row_431
    · exact weighted_row_435
    · exact weighted_row_439
    · exact weighted_row_443
    · exact weighted_row_447
    · exact weighted_row_451
    · exact weighted_row_455
    · exact weighted_row_459
    · exact weighted_row_463
    · exact weighted_row_467
    · exact weighted_row_471
    · exact weighted_row_475
    · exact weighted_row_479
    · exact weighted_row_483
    · exact weighted_row_487
    · exact weighted_row_491
    · exact weighted_row_495
    · exact weighted_row_499
    · exact weighted_row_503
    · exact weighted_row_507
    · exact weighted_row_511
    · exact weighted_row_515
    · exact weighted_row_519
    · exact weighted_row_523
    · exact weighted_row_527
    · exact weighted_row_531
    · exact weighted_row_535
    · exact weighted_row_539
    · exact weighted_row_543
    · exact weighted_row_547
    · exact weighted_row_551
    · exact weighted_row_555
    · exact weighted_row_559
    · exact weighted_row_563
    · exact weighted_row_567
    · exact weighted_row_571
    · exact weighted_row_575
    · exact weighted_row_579
    · exact weighted_row_583
    · exact weighted_row_587
    · exact weighted_row_591
    · exact weighted_row_595
    · exact weighted_row_599
    · exact weighted_row_603
    · exact weighted_row_607
    · exact weighted_row_611
    · exact weighted_row_615
    · exact weighted_row_619
    · exact weighted_row_623
    · exact weighted_row_627
    · exact weighted_row_631
    · exact weighted_row_635
    · exact weighted_row_639
    · exact weighted_row_643
    · exact weighted_row_647
    · exact weighted_row_651
    · exact weighted_row_655
    · exact weighted_row_659
    · exact weighted_row_663
    · exact weighted_row_667
    · exact weighted_row_671
    · exact weighted_row_675
    · exact weighted_row_679
    · exact weighted_row_683
    · exact weighted_row_687
    · exact weighted_row_691
    · exact weighted_row_695
    · exact weighted_row_699
    · exact weighted_row_703
    · exact weighted_row_707
    · exact weighted_row_711
    · exact weighted_row_715
    · exact weighted_row_719
    · exact weighted_row_723
    · exact weighted_row_727
    · exact weighted_row_731
    · exact weighted_row_735
    · exact weighted_row_739
    · exact weighted_row_743
    · exact weighted_row_747
    · exact weighted_row_751
    · exact weighted_row_755
    · exact weighted_row_759
    · exact weighted_row_763
    · exact weighted_row_767
    · exact weighted_row_771
    · exact weighted_row_775
    · exact weighted_row_779
    · exact weighted_row_783
    · exact weighted_row_787

theorem weightedRow_exact (u : Fin 788) : weightedSparseRow u = weightedRowExpected u := by
  let i : Fin 197 := ⟨u.val / 4, by omega⟩
  let h : Fin 4 := ⟨u.val % 4, by omega⟩
  have hu : blockIndex i h = u := by
    apply Fin.ext
    change 4 * (u.val / 4) + u.val % 4 = u.val
    omega
  rw [← hu]
  exact weightedRow_block i h

end Hedetniemi.Round4
