import Hedetniemi.Round4.SupportRows.Batch00
import Hedetniemi.Round4.SupportRows.Batch01
import Hedetniemi.Round4.SupportRows.Batch02
import Hedetniemi.Round4.SupportRows.Batch03
import Hedetniemi.Round4.SupportRows.Batch04
import Hedetniemi.Round4.SupportRows.Batch05
import Hedetniemi.Round4.SupportRows.Batch06
import Hedetniemi.Round4.SupportRows.Batch07
import Hedetniemi.Round4.SupportRows.Batch08
import Hedetniemi.Round4.SupportRows.Batch09
import Hedetniemi.Round4.SupportRows.Batch10
import Hedetniemi.Round4.SupportRows.Batch11
import Hedetniemi.Round4.SupportRows.Batch12
import Hedetniemi.Round4.SupportRows.Batch13
import Hedetniemi.Round4.SupportRows.Batch14
import Hedetniemi.Round4.SupportRows.Batch15
import Hedetniemi.Round4.SupportRows.Batch16
import Hedetniemi.Round4.SupportRows.Batch17
import Hedetniemi.Round4.SupportRows.Batch18
import Hedetniemi.Round4.SupportRows.Batch19
import Hedetniemi.Round4.SupportRows.Batch20
import Hedetniemi.Round4.SupportRows.Batch21
import Hedetniemi.Round4.SupportRows.Batch22
import Hedetniemi.Round4.SupportRows.Batch23
import Hedetniemi.Round4.SupportRows.Batch24
import Hedetniemi.Round4.SupportRows.Batch25
import Hedetniemi.Round4.SupportRows.Batch26
import Hedetniemi.Round4.SupportRows.Batch27
import Hedetniemi.Round4.SupportRows.Batch28
import Hedetniemi.Round4.SupportRows.Batch29
import Hedetniemi.Round4.SupportRows.Batch30
import Hedetniemi.Round4.SupportRows.Batch31
import Hedetniemi.Round4.SupportRows.Batch32
import Hedetniemi.Round4.SupportRows.Batch33
import Hedetniemi.Round4.SupportRows.Batch34
import Hedetniemi.Round4.SupportRows.Batch35
import Hedetniemi.Round4.SupportRows.Batch36
import Hedetniemi.Round4.SupportRows.Batch37
import Hedetniemi.Round4.SupportRows.Batch38
import Hedetniemi.Round4.SupportRows.Batch39
import Hedetniemi.Round4.SupportRows.Batch40
import Hedetniemi.Round4.SupportRows.Batch41
import Hedetniemi.Round4.SupportRows.Batch42
import Hedetniemi.Round4.SupportRows.Batch43
import Hedetniemi.Round4.SupportRows.Batch44
import Hedetniemi.Round4.SupportRows.Batch45
import Hedetniemi.Round4.SupportRows.Batch46
import Hedetniemi.Round4.SupportRows.Batch47
import Hedetniemi.Round4.SupportRows.Batch48
import Hedetniemi.Round4.SupportRows.Batch49
namespace Hedetniemi.Round4
set_option maxRecDepth 1000000
set_option maxHeartbeats 0
set_option exponentiation.threshold 100000
theorem kernel_support_all (s : Fin 4) (i j : Fin 197) : KernelSupportAt s i j := by
  fin_cases s
  · fin_cases i
    · exact kernel_support_row_0_0 j
    · exact kernel_support_row_0_1 j
    · exact kernel_support_row_0_2 j
    · exact kernel_support_row_0_3 j
    · exact kernel_support_row_0_4 j
    · exact kernel_support_row_0_5 j
    · exact kernel_support_row_0_6 j
    · exact kernel_support_row_0_7 j
    · exact kernel_support_row_0_8 j
    · exact kernel_support_row_0_9 j
    · exact kernel_support_row_0_10 j
    · exact kernel_support_row_0_11 j
    · exact kernel_support_row_0_12 j
    · exact kernel_support_row_0_13 j
    · exact kernel_support_row_0_14 j
    · exact kernel_support_row_0_15 j
    · exact kernel_support_row_0_16 j
    · exact kernel_support_row_0_17 j
    · exact kernel_support_row_0_18 j
    · exact kernel_support_row_0_19 j
    · exact kernel_support_row_0_20 j
    · exact kernel_support_row_0_21 j
    · exact kernel_support_row_0_22 j
    · exact kernel_support_row_0_23 j
    · exact kernel_support_row_0_24 j
    · exact kernel_support_row_0_25 j
    · exact kernel_support_row_0_26 j
    · exact kernel_support_row_0_27 j
    · exact kernel_support_row_0_28 j
    · exact kernel_support_row_0_29 j
    · exact kernel_support_row_0_30 j
    · exact kernel_support_row_0_31 j
    · exact kernel_support_row_0_32 j
    · exact kernel_support_row_0_33 j
    · exact kernel_support_row_0_34 j
    · exact kernel_support_row_0_35 j
    · exact kernel_support_row_0_36 j
    · exact kernel_support_row_0_37 j
    · exact kernel_support_row_0_38 j
    · exact kernel_support_row_0_39 j
    · exact kernel_support_row_0_40 j
    · exact kernel_support_row_0_41 j
    · exact kernel_support_row_0_42 j
    · exact kernel_support_row_0_43 j
    · exact kernel_support_row_0_44 j
    · exact kernel_support_row_0_45 j
    · exact kernel_support_row_0_46 j
    · exact kernel_support_row_0_47 j
    · exact kernel_support_row_0_48 j
    · exact kernel_support_row_0_49 j
    · exact kernel_support_row_0_50 j
    · exact kernel_support_row_0_51 j
    · exact kernel_support_row_0_52 j
    · exact kernel_support_row_0_53 j
    · exact kernel_support_row_0_54 j
    · exact kernel_support_row_0_55 j
    · exact kernel_support_row_0_56 j
    · exact kernel_support_row_0_57 j
    · exact kernel_support_row_0_58 j
    · exact kernel_support_row_0_59 j
    · exact kernel_support_row_0_60 j
    · exact kernel_support_row_0_61 j
    · exact kernel_support_row_0_62 j
    · exact kernel_support_row_0_63 j
    · exact kernel_support_row_0_64 j
    · exact kernel_support_row_0_65 j
    · exact kernel_support_row_0_66 j
    · exact kernel_support_row_0_67 j
    · exact kernel_support_row_0_68 j
    · exact kernel_support_row_0_69 j
    · exact kernel_support_row_0_70 j
    · exact kernel_support_row_0_71 j
    · exact kernel_support_row_0_72 j
    · exact kernel_support_row_0_73 j
    · exact kernel_support_row_0_74 j
    · exact kernel_support_row_0_75 j
    · exact kernel_support_row_0_76 j
    · exact kernel_support_row_0_77 j
    · exact kernel_support_row_0_78 j
    · exact kernel_support_row_0_79 j
    · exact kernel_support_row_0_80 j
    · exact kernel_support_row_0_81 j
    · exact kernel_support_row_0_82 j
    · exact kernel_support_row_0_83 j
    · exact kernel_support_row_0_84 j
    · exact kernel_support_row_0_85 j
    · exact kernel_support_row_0_86 j
    · exact kernel_support_row_0_87 j
    · exact kernel_support_row_0_88 j
    · exact kernel_support_row_0_89 j
    · exact kernel_support_row_0_90 j
    · exact kernel_support_row_0_91 j
    · exact kernel_support_row_0_92 j
    · exact kernel_support_row_0_93 j
    · exact kernel_support_row_0_94 j
    · exact kernel_support_row_0_95 j
    · exact kernel_support_row_0_96 j
    · exact kernel_support_row_0_97 j
    · exact kernel_support_row_0_98 j
    · exact kernel_support_row_0_99 j
    · exact kernel_support_row_0_100 j
    · exact kernel_support_row_0_101 j
    · exact kernel_support_row_0_102 j
    · exact kernel_support_row_0_103 j
    · exact kernel_support_row_0_104 j
    · exact kernel_support_row_0_105 j
    · exact kernel_support_row_0_106 j
    · exact kernel_support_row_0_107 j
    · exact kernel_support_row_0_108 j
    · exact kernel_support_row_0_109 j
    · exact kernel_support_row_0_110 j
    · exact kernel_support_row_0_111 j
    · exact kernel_support_row_0_112 j
    · exact kernel_support_row_0_113 j
    · exact kernel_support_row_0_114 j
    · exact kernel_support_row_0_115 j
    · exact kernel_support_row_0_116 j
    · exact kernel_support_row_0_117 j
    · exact kernel_support_row_0_118 j
    · exact kernel_support_row_0_119 j
    · exact kernel_support_row_0_120 j
    · exact kernel_support_row_0_121 j
    · exact kernel_support_row_0_122 j
    · exact kernel_support_row_0_123 j
    · exact kernel_support_row_0_124 j
    · exact kernel_support_row_0_125 j
    · exact kernel_support_row_0_126 j
    · exact kernel_support_row_0_127 j
    · exact kernel_support_row_0_128 j
    · exact kernel_support_row_0_129 j
    · exact kernel_support_row_0_130 j
    · exact kernel_support_row_0_131 j
    · exact kernel_support_row_0_132 j
    · exact kernel_support_row_0_133 j
    · exact kernel_support_row_0_134 j
    · exact kernel_support_row_0_135 j
    · exact kernel_support_row_0_136 j
    · exact kernel_support_row_0_137 j
    · exact kernel_support_row_0_138 j
    · exact kernel_support_row_0_139 j
    · exact kernel_support_row_0_140 j
    · exact kernel_support_row_0_141 j
    · exact kernel_support_row_0_142 j
    · exact kernel_support_row_0_143 j
    · exact kernel_support_row_0_144 j
    · exact kernel_support_row_0_145 j
    · exact kernel_support_row_0_146 j
    · exact kernel_support_row_0_147 j
    · exact kernel_support_row_0_148 j
    · exact kernel_support_row_0_149 j
    · exact kernel_support_row_0_150 j
    · exact kernel_support_row_0_151 j
    · exact kernel_support_row_0_152 j
    · exact kernel_support_row_0_153 j
    · exact kernel_support_row_0_154 j
    · exact kernel_support_row_0_155 j
    · exact kernel_support_row_0_156 j
    · exact kernel_support_row_0_157 j
    · exact kernel_support_row_0_158 j
    · exact kernel_support_row_0_159 j
    · exact kernel_support_row_0_160 j
    · exact kernel_support_row_0_161 j
    · exact kernel_support_row_0_162 j
    · exact kernel_support_row_0_163 j
    · exact kernel_support_row_0_164 j
    · exact kernel_support_row_0_165 j
    · exact kernel_support_row_0_166 j
    · exact kernel_support_row_0_167 j
    · exact kernel_support_row_0_168 j
    · exact kernel_support_row_0_169 j
    · exact kernel_support_row_0_170 j
    · exact kernel_support_row_0_171 j
    · exact kernel_support_row_0_172 j
    · exact kernel_support_row_0_173 j
    · exact kernel_support_row_0_174 j
    · exact kernel_support_row_0_175 j
    · exact kernel_support_row_0_176 j
    · exact kernel_support_row_0_177 j
    · exact kernel_support_row_0_178 j
    · exact kernel_support_row_0_179 j
    · exact kernel_support_row_0_180 j
    · exact kernel_support_row_0_181 j
    · exact kernel_support_row_0_182 j
    · exact kernel_support_row_0_183 j
    · exact kernel_support_row_0_184 j
    · exact kernel_support_row_0_185 j
    · exact kernel_support_row_0_186 j
    · exact kernel_support_row_0_187 j
    · exact kernel_support_row_0_188 j
    · exact kernel_support_row_0_189 j
    · exact kernel_support_row_0_190 j
    · exact kernel_support_row_0_191 j
    · exact kernel_support_row_0_192 j
    · exact kernel_support_row_0_193 j
    · exact kernel_support_row_0_194 j
    · exact kernel_support_row_0_195 j
    · exact kernel_support_row_0_196 j
  · fin_cases i
    · exact kernel_support_row_1_0 j
    · exact kernel_support_row_1_1 j
    · exact kernel_support_row_1_2 j
    · exact kernel_support_row_1_3 j
    · exact kernel_support_row_1_4 j
    · exact kernel_support_row_1_5 j
    · exact kernel_support_row_1_6 j
    · exact kernel_support_row_1_7 j
    · exact kernel_support_row_1_8 j
    · exact kernel_support_row_1_9 j
    · exact kernel_support_row_1_10 j
    · exact kernel_support_row_1_11 j
    · exact kernel_support_row_1_12 j
    · exact kernel_support_row_1_13 j
    · exact kernel_support_row_1_14 j
    · exact kernel_support_row_1_15 j
    · exact kernel_support_row_1_16 j
    · exact kernel_support_row_1_17 j
    · exact kernel_support_row_1_18 j
    · exact kernel_support_row_1_19 j
    · exact kernel_support_row_1_20 j
    · exact kernel_support_row_1_21 j
    · exact kernel_support_row_1_22 j
    · exact kernel_support_row_1_23 j
    · exact kernel_support_row_1_24 j
    · exact kernel_support_row_1_25 j
    · exact kernel_support_row_1_26 j
    · exact kernel_support_row_1_27 j
    · exact kernel_support_row_1_28 j
    · exact kernel_support_row_1_29 j
    · exact kernel_support_row_1_30 j
    · exact kernel_support_row_1_31 j
    · exact kernel_support_row_1_32 j
    · exact kernel_support_row_1_33 j
    · exact kernel_support_row_1_34 j
    · exact kernel_support_row_1_35 j
    · exact kernel_support_row_1_36 j
    · exact kernel_support_row_1_37 j
    · exact kernel_support_row_1_38 j
    · exact kernel_support_row_1_39 j
    · exact kernel_support_row_1_40 j
    · exact kernel_support_row_1_41 j
    · exact kernel_support_row_1_42 j
    · exact kernel_support_row_1_43 j
    · exact kernel_support_row_1_44 j
    · exact kernel_support_row_1_45 j
    · exact kernel_support_row_1_46 j
    · exact kernel_support_row_1_47 j
    · exact kernel_support_row_1_48 j
    · exact kernel_support_row_1_49 j
    · exact kernel_support_row_1_50 j
    · exact kernel_support_row_1_51 j
    · exact kernel_support_row_1_52 j
    · exact kernel_support_row_1_53 j
    · exact kernel_support_row_1_54 j
    · exact kernel_support_row_1_55 j
    · exact kernel_support_row_1_56 j
    · exact kernel_support_row_1_57 j
    · exact kernel_support_row_1_58 j
    · exact kernel_support_row_1_59 j
    · exact kernel_support_row_1_60 j
    · exact kernel_support_row_1_61 j
    · exact kernel_support_row_1_62 j
    · exact kernel_support_row_1_63 j
    · exact kernel_support_row_1_64 j
    · exact kernel_support_row_1_65 j
    · exact kernel_support_row_1_66 j
    · exact kernel_support_row_1_67 j
    · exact kernel_support_row_1_68 j
    · exact kernel_support_row_1_69 j
    · exact kernel_support_row_1_70 j
    · exact kernel_support_row_1_71 j
    · exact kernel_support_row_1_72 j
    · exact kernel_support_row_1_73 j
    · exact kernel_support_row_1_74 j
    · exact kernel_support_row_1_75 j
    · exact kernel_support_row_1_76 j
    · exact kernel_support_row_1_77 j
    · exact kernel_support_row_1_78 j
    · exact kernel_support_row_1_79 j
    · exact kernel_support_row_1_80 j
    · exact kernel_support_row_1_81 j
    · exact kernel_support_row_1_82 j
    · exact kernel_support_row_1_83 j
    · exact kernel_support_row_1_84 j
    · exact kernel_support_row_1_85 j
    · exact kernel_support_row_1_86 j
    · exact kernel_support_row_1_87 j
    · exact kernel_support_row_1_88 j
    · exact kernel_support_row_1_89 j
    · exact kernel_support_row_1_90 j
    · exact kernel_support_row_1_91 j
    · exact kernel_support_row_1_92 j
    · exact kernel_support_row_1_93 j
    · exact kernel_support_row_1_94 j
    · exact kernel_support_row_1_95 j
    · exact kernel_support_row_1_96 j
    · exact kernel_support_row_1_97 j
    · exact kernel_support_row_1_98 j
    · exact kernel_support_row_1_99 j
    · exact kernel_support_row_1_100 j
    · exact kernel_support_row_1_101 j
    · exact kernel_support_row_1_102 j
    · exact kernel_support_row_1_103 j
    · exact kernel_support_row_1_104 j
    · exact kernel_support_row_1_105 j
    · exact kernel_support_row_1_106 j
    · exact kernel_support_row_1_107 j
    · exact kernel_support_row_1_108 j
    · exact kernel_support_row_1_109 j
    · exact kernel_support_row_1_110 j
    · exact kernel_support_row_1_111 j
    · exact kernel_support_row_1_112 j
    · exact kernel_support_row_1_113 j
    · exact kernel_support_row_1_114 j
    · exact kernel_support_row_1_115 j
    · exact kernel_support_row_1_116 j
    · exact kernel_support_row_1_117 j
    · exact kernel_support_row_1_118 j
    · exact kernel_support_row_1_119 j
    · exact kernel_support_row_1_120 j
    · exact kernel_support_row_1_121 j
    · exact kernel_support_row_1_122 j
    · exact kernel_support_row_1_123 j
    · exact kernel_support_row_1_124 j
    · exact kernel_support_row_1_125 j
    · exact kernel_support_row_1_126 j
    · exact kernel_support_row_1_127 j
    · exact kernel_support_row_1_128 j
    · exact kernel_support_row_1_129 j
    · exact kernel_support_row_1_130 j
    · exact kernel_support_row_1_131 j
    · exact kernel_support_row_1_132 j
    · exact kernel_support_row_1_133 j
    · exact kernel_support_row_1_134 j
    · exact kernel_support_row_1_135 j
    · exact kernel_support_row_1_136 j
    · exact kernel_support_row_1_137 j
    · exact kernel_support_row_1_138 j
    · exact kernel_support_row_1_139 j
    · exact kernel_support_row_1_140 j
    · exact kernel_support_row_1_141 j
    · exact kernel_support_row_1_142 j
    · exact kernel_support_row_1_143 j
    · exact kernel_support_row_1_144 j
    · exact kernel_support_row_1_145 j
    · exact kernel_support_row_1_146 j
    · exact kernel_support_row_1_147 j
    · exact kernel_support_row_1_148 j
    · exact kernel_support_row_1_149 j
    · exact kernel_support_row_1_150 j
    · exact kernel_support_row_1_151 j
    · exact kernel_support_row_1_152 j
    · exact kernel_support_row_1_153 j
    · exact kernel_support_row_1_154 j
    · exact kernel_support_row_1_155 j
    · exact kernel_support_row_1_156 j
    · exact kernel_support_row_1_157 j
    · exact kernel_support_row_1_158 j
    · exact kernel_support_row_1_159 j
    · exact kernel_support_row_1_160 j
    · exact kernel_support_row_1_161 j
    · exact kernel_support_row_1_162 j
    · exact kernel_support_row_1_163 j
    · exact kernel_support_row_1_164 j
    · exact kernel_support_row_1_165 j
    · exact kernel_support_row_1_166 j
    · exact kernel_support_row_1_167 j
    · exact kernel_support_row_1_168 j
    · exact kernel_support_row_1_169 j
    · exact kernel_support_row_1_170 j
    · exact kernel_support_row_1_171 j
    · exact kernel_support_row_1_172 j
    · exact kernel_support_row_1_173 j
    · exact kernel_support_row_1_174 j
    · exact kernel_support_row_1_175 j
    · exact kernel_support_row_1_176 j
    · exact kernel_support_row_1_177 j
    · exact kernel_support_row_1_178 j
    · exact kernel_support_row_1_179 j
    · exact kernel_support_row_1_180 j
    · exact kernel_support_row_1_181 j
    · exact kernel_support_row_1_182 j
    · exact kernel_support_row_1_183 j
    · exact kernel_support_row_1_184 j
    · exact kernel_support_row_1_185 j
    · exact kernel_support_row_1_186 j
    · exact kernel_support_row_1_187 j
    · exact kernel_support_row_1_188 j
    · exact kernel_support_row_1_189 j
    · exact kernel_support_row_1_190 j
    · exact kernel_support_row_1_191 j
    · exact kernel_support_row_1_192 j
    · exact kernel_support_row_1_193 j
    · exact kernel_support_row_1_194 j
    · exact kernel_support_row_1_195 j
    · exact kernel_support_row_1_196 j
  · fin_cases i
    · exact kernel_support_row_2_0 j
    · exact kernel_support_row_2_1 j
    · exact kernel_support_row_2_2 j
    · exact kernel_support_row_2_3 j
    · exact kernel_support_row_2_4 j
    · exact kernel_support_row_2_5 j
    · exact kernel_support_row_2_6 j
    · exact kernel_support_row_2_7 j
    · exact kernel_support_row_2_8 j
    · exact kernel_support_row_2_9 j
    · exact kernel_support_row_2_10 j
    · exact kernel_support_row_2_11 j
    · exact kernel_support_row_2_12 j
    · exact kernel_support_row_2_13 j
    · exact kernel_support_row_2_14 j
    · exact kernel_support_row_2_15 j
    · exact kernel_support_row_2_16 j
    · exact kernel_support_row_2_17 j
    · exact kernel_support_row_2_18 j
    · exact kernel_support_row_2_19 j
    · exact kernel_support_row_2_20 j
    · exact kernel_support_row_2_21 j
    · exact kernel_support_row_2_22 j
    · exact kernel_support_row_2_23 j
    · exact kernel_support_row_2_24 j
    · exact kernel_support_row_2_25 j
    · exact kernel_support_row_2_26 j
    · exact kernel_support_row_2_27 j
    · exact kernel_support_row_2_28 j
    · exact kernel_support_row_2_29 j
    · exact kernel_support_row_2_30 j
    · exact kernel_support_row_2_31 j
    · exact kernel_support_row_2_32 j
    · exact kernel_support_row_2_33 j
    · exact kernel_support_row_2_34 j
    · exact kernel_support_row_2_35 j
    · exact kernel_support_row_2_36 j
    · exact kernel_support_row_2_37 j
    · exact kernel_support_row_2_38 j
    · exact kernel_support_row_2_39 j
    · exact kernel_support_row_2_40 j
    · exact kernel_support_row_2_41 j
    · exact kernel_support_row_2_42 j
    · exact kernel_support_row_2_43 j
    · exact kernel_support_row_2_44 j
    · exact kernel_support_row_2_45 j
    · exact kernel_support_row_2_46 j
    · exact kernel_support_row_2_47 j
    · exact kernel_support_row_2_48 j
    · exact kernel_support_row_2_49 j
    · exact kernel_support_row_2_50 j
    · exact kernel_support_row_2_51 j
    · exact kernel_support_row_2_52 j
    · exact kernel_support_row_2_53 j
    · exact kernel_support_row_2_54 j
    · exact kernel_support_row_2_55 j
    · exact kernel_support_row_2_56 j
    · exact kernel_support_row_2_57 j
    · exact kernel_support_row_2_58 j
    · exact kernel_support_row_2_59 j
    · exact kernel_support_row_2_60 j
    · exact kernel_support_row_2_61 j
    · exact kernel_support_row_2_62 j
    · exact kernel_support_row_2_63 j
    · exact kernel_support_row_2_64 j
    · exact kernel_support_row_2_65 j
    · exact kernel_support_row_2_66 j
    · exact kernel_support_row_2_67 j
    · exact kernel_support_row_2_68 j
    · exact kernel_support_row_2_69 j
    · exact kernel_support_row_2_70 j
    · exact kernel_support_row_2_71 j
    · exact kernel_support_row_2_72 j
    · exact kernel_support_row_2_73 j
    · exact kernel_support_row_2_74 j
    · exact kernel_support_row_2_75 j
    · exact kernel_support_row_2_76 j
    · exact kernel_support_row_2_77 j
    · exact kernel_support_row_2_78 j
    · exact kernel_support_row_2_79 j
    · exact kernel_support_row_2_80 j
    · exact kernel_support_row_2_81 j
    · exact kernel_support_row_2_82 j
    · exact kernel_support_row_2_83 j
    · exact kernel_support_row_2_84 j
    · exact kernel_support_row_2_85 j
    · exact kernel_support_row_2_86 j
    · exact kernel_support_row_2_87 j
    · exact kernel_support_row_2_88 j
    · exact kernel_support_row_2_89 j
    · exact kernel_support_row_2_90 j
    · exact kernel_support_row_2_91 j
    · exact kernel_support_row_2_92 j
    · exact kernel_support_row_2_93 j
    · exact kernel_support_row_2_94 j
    · exact kernel_support_row_2_95 j
    · exact kernel_support_row_2_96 j
    · exact kernel_support_row_2_97 j
    · exact kernel_support_row_2_98 j
    · exact kernel_support_row_2_99 j
    · exact kernel_support_row_2_100 j
    · exact kernel_support_row_2_101 j
    · exact kernel_support_row_2_102 j
    · exact kernel_support_row_2_103 j
    · exact kernel_support_row_2_104 j
    · exact kernel_support_row_2_105 j
    · exact kernel_support_row_2_106 j
    · exact kernel_support_row_2_107 j
    · exact kernel_support_row_2_108 j
    · exact kernel_support_row_2_109 j
    · exact kernel_support_row_2_110 j
    · exact kernel_support_row_2_111 j
    · exact kernel_support_row_2_112 j
    · exact kernel_support_row_2_113 j
    · exact kernel_support_row_2_114 j
    · exact kernel_support_row_2_115 j
    · exact kernel_support_row_2_116 j
    · exact kernel_support_row_2_117 j
    · exact kernel_support_row_2_118 j
    · exact kernel_support_row_2_119 j
    · exact kernel_support_row_2_120 j
    · exact kernel_support_row_2_121 j
    · exact kernel_support_row_2_122 j
    · exact kernel_support_row_2_123 j
    · exact kernel_support_row_2_124 j
    · exact kernel_support_row_2_125 j
    · exact kernel_support_row_2_126 j
    · exact kernel_support_row_2_127 j
    · exact kernel_support_row_2_128 j
    · exact kernel_support_row_2_129 j
    · exact kernel_support_row_2_130 j
    · exact kernel_support_row_2_131 j
    · exact kernel_support_row_2_132 j
    · exact kernel_support_row_2_133 j
    · exact kernel_support_row_2_134 j
    · exact kernel_support_row_2_135 j
    · exact kernel_support_row_2_136 j
    · exact kernel_support_row_2_137 j
    · exact kernel_support_row_2_138 j
    · exact kernel_support_row_2_139 j
    · exact kernel_support_row_2_140 j
    · exact kernel_support_row_2_141 j
    · exact kernel_support_row_2_142 j
    · exact kernel_support_row_2_143 j
    · exact kernel_support_row_2_144 j
    · exact kernel_support_row_2_145 j
    · exact kernel_support_row_2_146 j
    · exact kernel_support_row_2_147 j
    · exact kernel_support_row_2_148 j
    · exact kernel_support_row_2_149 j
    · exact kernel_support_row_2_150 j
    · exact kernel_support_row_2_151 j
    · exact kernel_support_row_2_152 j
    · exact kernel_support_row_2_153 j
    · exact kernel_support_row_2_154 j
    · exact kernel_support_row_2_155 j
    · exact kernel_support_row_2_156 j
    · exact kernel_support_row_2_157 j
    · exact kernel_support_row_2_158 j
    · exact kernel_support_row_2_159 j
    · exact kernel_support_row_2_160 j
    · exact kernel_support_row_2_161 j
    · exact kernel_support_row_2_162 j
    · exact kernel_support_row_2_163 j
    · exact kernel_support_row_2_164 j
    · exact kernel_support_row_2_165 j
    · exact kernel_support_row_2_166 j
    · exact kernel_support_row_2_167 j
    · exact kernel_support_row_2_168 j
    · exact kernel_support_row_2_169 j
    · exact kernel_support_row_2_170 j
    · exact kernel_support_row_2_171 j
    · exact kernel_support_row_2_172 j
    · exact kernel_support_row_2_173 j
    · exact kernel_support_row_2_174 j
    · exact kernel_support_row_2_175 j
    · exact kernel_support_row_2_176 j
    · exact kernel_support_row_2_177 j
    · exact kernel_support_row_2_178 j
    · exact kernel_support_row_2_179 j
    · exact kernel_support_row_2_180 j
    · exact kernel_support_row_2_181 j
    · exact kernel_support_row_2_182 j
    · exact kernel_support_row_2_183 j
    · exact kernel_support_row_2_184 j
    · exact kernel_support_row_2_185 j
    · exact kernel_support_row_2_186 j
    · exact kernel_support_row_2_187 j
    · exact kernel_support_row_2_188 j
    · exact kernel_support_row_2_189 j
    · exact kernel_support_row_2_190 j
    · exact kernel_support_row_2_191 j
    · exact kernel_support_row_2_192 j
    · exact kernel_support_row_2_193 j
    · exact kernel_support_row_2_194 j
    · exact kernel_support_row_2_195 j
    · exact kernel_support_row_2_196 j
  · fin_cases i
    · exact kernel_support_row_3_0 j
    · exact kernel_support_row_3_1 j
    · exact kernel_support_row_3_2 j
    · exact kernel_support_row_3_3 j
    · exact kernel_support_row_3_4 j
    · exact kernel_support_row_3_5 j
    · exact kernel_support_row_3_6 j
    · exact kernel_support_row_3_7 j
    · exact kernel_support_row_3_8 j
    · exact kernel_support_row_3_9 j
    · exact kernel_support_row_3_10 j
    · exact kernel_support_row_3_11 j
    · exact kernel_support_row_3_12 j
    · exact kernel_support_row_3_13 j
    · exact kernel_support_row_3_14 j
    · exact kernel_support_row_3_15 j
    · exact kernel_support_row_3_16 j
    · exact kernel_support_row_3_17 j
    · exact kernel_support_row_3_18 j
    · exact kernel_support_row_3_19 j
    · exact kernel_support_row_3_20 j
    · exact kernel_support_row_3_21 j
    · exact kernel_support_row_3_22 j
    · exact kernel_support_row_3_23 j
    · exact kernel_support_row_3_24 j
    · exact kernel_support_row_3_25 j
    · exact kernel_support_row_3_26 j
    · exact kernel_support_row_3_27 j
    · exact kernel_support_row_3_28 j
    · exact kernel_support_row_3_29 j
    · exact kernel_support_row_3_30 j
    · exact kernel_support_row_3_31 j
    · exact kernel_support_row_3_32 j
    · exact kernel_support_row_3_33 j
    · exact kernel_support_row_3_34 j
    · exact kernel_support_row_3_35 j
    · exact kernel_support_row_3_36 j
    · exact kernel_support_row_3_37 j
    · exact kernel_support_row_3_38 j
    · exact kernel_support_row_3_39 j
    · exact kernel_support_row_3_40 j
    · exact kernel_support_row_3_41 j
    · exact kernel_support_row_3_42 j
    · exact kernel_support_row_3_43 j
    · exact kernel_support_row_3_44 j
    · exact kernel_support_row_3_45 j
    · exact kernel_support_row_3_46 j
    · exact kernel_support_row_3_47 j
    · exact kernel_support_row_3_48 j
    · exact kernel_support_row_3_49 j
    · exact kernel_support_row_3_50 j
    · exact kernel_support_row_3_51 j
    · exact kernel_support_row_3_52 j
    · exact kernel_support_row_3_53 j
    · exact kernel_support_row_3_54 j
    · exact kernel_support_row_3_55 j
    · exact kernel_support_row_3_56 j
    · exact kernel_support_row_3_57 j
    · exact kernel_support_row_3_58 j
    · exact kernel_support_row_3_59 j
    · exact kernel_support_row_3_60 j
    · exact kernel_support_row_3_61 j
    · exact kernel_support_row_3_62 j
    · exact kernel_support_row_3_63 j
    · exact kernel_support_row_3_64 j
    · exact kernel_support_row_3_65 j
    · exact kernel_support_row_3_66 j
    · exact kernel_support_row_3_67 j
    · exact kernel_support_row_3_68 j
    · exact kernel_support_row_3_69 j
    · exact kernel_support_row_3_70 j
    · exact kernel_support_row_3_71 j
    · exact kernel_support_row_3_72 j
    · exact kernel_support_row_3_73 j
    · exact kernel_support_row_3_74 j
    · exact kernel_support_row_3_75 j
    · exact kernel_support_row_3_76 j
    · exact kernel_support_row_3_77 j
    · exact kernel_support_row_3_78 j
    · exact kernel_support_row_3_79 j
    · exact kernel_support_row_3_80 j
    · exact kernel_support_row_3_81 j
    · exact kernel_support_row_3_82 j
    · exact kernel_support_row_3_83 j
    · exact kernel_support_row_3_84 j
    · exact kernel_support_row_3_85 j
    · exact kernel_support_row_3_86 j
    · exact kernel_support_row_3_87 j
    · exact kernel_support_row_3_88 j
    · exact kernel_support_row_3_89 j
    · exact kernel_support_row_3_90 j
    · exact kernel_support_row_3_91 j
    · exact kernel_support_row_3_92 j
    · exact kernel_support_row_3_93 j
    · exact kernel_support_row_3_94 j
    · exact kernel_support_row_3_95 j
    · exact kernel_support_row_3_96 j
    · exact kernel_support_row_3_97 j
    · exact kernel_support_row_3_98 j
    · exact kernel_support_row_3_99 j
    · exact kernel_support_row_3_100 j
    · exact kernel_support_row_3_101 j
    · exact kernel_support_row_3_102 j
    · exact kernel_support_row_3_103 j
    · exact kernel_support_row_3_104 j
    · exact kernel_support_row_3_105 j
    · exact kernel_support_row_3_106 j
    · exact kernel_support_row_3_107 j
    · exact kernel_support_row_3_108 j
    · exact kernel_support_row_3_109 j
    · exact kernel_support_row_3_110 j
    · exact kernel_support_row_3_111 j
    · exact kernel_support_row_3_112 j
    · exact kernel_support_row_3_113 j
    · exact kernel_support_row_3_114 j
    · exact kernel_support_row_3_115 j
    · exact kernel_support_row_3_116 j
    · exact kernel_support_row_3_117 j
    · exact kernel_support_row_3_118 j
    · exact kernel_support_row_3_119 j
    · exact kernel_support_row_3_120 j
    · exact kernel_support_row_3_121 j
    · exact kernel_support_row_3_122 j
    · exact kernel_support_row_3_123 j
    · exact kernel_support_row_3_124 j
    · exact kernel_support_row_3_125 j
    · exact kernel_support_row_3_126 j
    · exact kernel_support_row_3_127 j
    · exact kernel_support_row_3_128 j
    · exact kernel_support_row_3_129 j
    · exact kernel_support_row_3_130 j
    · exact kernel_support_row_3_131 j
    · exact kernel_support_row_3_132 j
    · exact kernel_support_row_3_133 j
    · exact kernel_support_row_3_134 j
    · exact kernel_support_row_3_135 j
    · exact kernel_support_row_3_136 j
    · exact kernel_support_row_3_137 j
    · exact kernel_support_row_3_138 j
    · exact kernel_support_row_3_139 j
    · exact kernel_support_row_3_140 j
    · exact kernel_support_row_3_141 j
    · exact kernel_support_row_3_142 j
    · exact kernel_support_row_3_143 j
    · exact kernel_support_row_3_144 j
    · exact kernel_support_row_3_145 j
    · exact kernel_support_row_3_146 j
    · exact kernel_support_row_3_147 j
    · exact kernel_support_row_3_148 j
    · exact kernel_support_row_3_149 j
    · exact kernel_support_row_3_150 j
    · exact kernel_support_row_3_151 j
    · exact kernel_support_row_3_152 j
    · exact kernel_support_row_3_153 j
    · exact kernel_support_row_3_154 j
    · exact kernel_support_row_3_155 j
    · exact kernel_support_row_3_156 j
    · exact kernel_support_row_3_157 j
    · exact kernel_support_row_3_158 j
    · exact kernel_support_row_3_159 j
    · exact kernel_support_row_3_160 j
    · exact kernel_support_row_3_161 j
    · exact kernel_support_row_3_162 j
    · exact kernel_support_row_3_163 j
    · exact kernel_support_row_3_164 j
    · exact kernel_support_row_3_165 j
    · exact kernel_support_row_3_166 j
    · exact kernel_support_row_3_167 j
    · exact kernel_support_row_3_168 j
    · exact kernel_support_row_3_169 j
    · exact kernel_support_row_3_170 j
    · exact kernel_support_row_3_171 j
    · exact kernel_support_row_3_172 j
    · exact kernel_support_row_3_173 j
    · exact kernel_support_row_3_174 j
    · exact kernel_support_row_3_175 j
    · exact kernel_support_row_3_176 j
    · exact kernel_support_row_3_177 j
    · exact kernel_support_row_3_178 j
    · exact kernel_support_row_3_179 j
    · exact kernel_support_row_3_180 j
    · exact kernel_support_row_3_181 j
    · exact kernel_support_row_3_182 j
    · exact kernel_support_row_3_183 j
    · exact kernel_support_row_3_184 j
    · exact kernel_support_row_3_185 j
    · exact kernel_support_row_3_186 j
    · exact kernel_support_row_3_187 j
    · exact kernel_support_row_3_188 j
    · exact kernel_support_row_3_189 j
    · exact kernel_support_row_3_190 j
    · exact kernel_support_row_3_191 j
    · exact kernel_support_row_3_192 j
    · exact kernel_support_row_3_193 j
    · exact kernel_support_row_3_194 j
    · exact kernel_support_row_3_195 j
    · exact kernel_support_row_3_196 j
end Hedetniemi.Round4
